window.PROJECT_INFO = {
  "title": "Omni Demand Understanding: A Benchmark for Situated User-Intent Inference in Multimodal Interaction",
  "name": "Omni Demand Understanding",
  "subtitle": "A Benchmark for Situated User-Intent Inference in Multimodal Interaction",
  "abstract_html": "\u003cp>As Multimodal Large Language Models (MLLMs) become more widely used in human--machine interaction, benchmarks of their interactive capabilities still focus primarily on response quality, leaving a more fundamental question underexplored: \u003cem>whether a model can correctly infer the user demand behind a complex audio--visual user query\u003c/em>. Real-world user demands are often not fully specified in what the user says and must be inferred from multimodal cues and dialogue history. This inference is further complicated by ambiguous or disfluent expression and noisy acoustic environments. Conversely, request-like speech may not constitute a demand to the assistant, leading to false triggers. To systematically evaluate this capability, we introduce \u003cstrong>Omni Demand Understanding (ODU)\u003c/strong>. Given a multimodal interaction stream, a model must detect whether a user demand is present and infer the user&#x27;s intent from multimodal and conversational context. ODU evaluates this capability along five dimensions, covering both single-turn and multi-turn interactions. We develop a taxonomy of challenging demand-understanding scenarios and a taxonomy-driven agentic video-generation pipeline for creating diverse and controllable interactions. We also complement synthetic interactions with realistic human-recorded interactions to ensure behavioral and acoustic realism. All media undergo careful annotation and manual quality control. We evaluate 14 native audio and audio--visual MLLMs. Even the strongest, Gemini 3.1 Pro, recovers only 44.7% of the key information that must be inferred from visual, acoustic, or conversational context. Moreover, 11 of the 14 models exhibit false-trigger rates above 50% on non-demand scenarios. Together, these results reveal a systematic capability gap in current MLLMs&#x27; ability to understand situated user demands. We hope ODU will help establish the evaluation of a previously underexplored yet essential capability in multimodal interaction: correctly understanding user demands before generating an appropriate response.\u003c/p>",
  "scene_count": 2078,
  "recorded_count": 277,
  "ethics": [
    "Human-recorded interactions were performed by paid actors. Before release, all participating actors signed informed-consent forms authorizing use of their recording data, including their faces and voices, for academic evaluation and public release with the benchmark. To protect actor privacy, the released human-recorded interactions may be used solely to evaluate systems on this benchmark; all other academic and commercial uses are prohibited. Generated scenes contain no real individuals."
  ]
};
