window.PROJECT_INFO = {
  "title": "Omni Demand Understanding: A Benchmark for Situated User-Intent Inference in Multimodal Interaction",
  "name": "Omni Demand Understanding",
  "subtitle": "A Benchmark for Situated User-Intent Inference in Multimodal Interaction",
  "abstract_html": "\u003cp>Natural audio--visual interaction is emerging as an important interface for AI assistants, allowing users to communicate through speech and vision rather than carefully composed text prompts. However, existing benchmarks of interactive capabilities still focus primarily on response quality, leaving a more fundamental question underexplored: \u003cem>can a model correctly infer the user&#x27;s underlying demand from a complex multimodal interaction?\u003c/em> Real-world user demands are often underspecified in speech and must be inferred from multimodal cues and dialogue history. This inference is further complicated by ambiguous or disfluent expression and noisy acoustic environments. Conversely, request-like speech may not constitute a demand to the assistant, leading to false triggers. We establish \u003cstrong>Omni Demand Understanding (ODU)\u003c/strong> as a distinct multimodal contextual inference problem: given an interaction stream, a model must detect whether a user demand is present and infer the user&#x27;s intent from multimodal and conversational context. ODU evaluates this capability along five dimensions, covering both single-turn and multi-turn interactions. We construct ODU-Bench using a challenge-driven taxonomy, taxonomy-guided agentic video generation, and human-recorded interactions, followed by media-grounded annotation and human verification. We evaluate 14 native audio and audio--visual MLLMs. Even the strongest, Gemini 3.1 Pro, recovers only 44.7% of the key information that must be inferred from visual, acoustic, or conversational context. Moreover, 11 of the 14 models exhibit false-trigger rates above 50% on non-demand scenarios. These results reveal a systematic capability gap in current MLLMs&#x27; ability to infer contextual user demands. We hope ODU can establish the evaluation of a previously underexplored yet essential capability in multimodal interaction: correctly understanding user demands before generating an appropriate response.\u003c/p>",
  "scene_count": 2078,
  "recorded_count": 277,
  "ethics": [
    "Human-recorded interactions were performed by paid actors. Before release, all participating actors signed informed-consent forms authorizing use of their recording data, including their faces and voices, for academic evaluation and public release with the benchmark. To protect actor privacy, the released human-recorded interactions may be used solely to evaluate systems on this benchmark; all other academic and commercial uses are prohibited. Generated scenes contain no real individuals. ODU-Bench is provided solely for academic research and model evaluation, subject to the above restrictions on human-recorded interactions. Commercial use of the dataset or its images in products, services, or other profit-making activities is prohibited. Images in the dataset may depict identifiable individuals; copyright and related rights remain with their respective rights holders. The release does not authorize sublicensing, commercial exploitation, or the creation of derivative works from these images. Users must comply with the release terms, the scope of participant consent, and applicable personal information protection and portrait rights laws and regulations."
  ]
};
